POST http://localhost:8000/set
accept: application/json
Content-Type: application/json

{
    "key": "string",
    "value": "hello world",
    "expire": 0
}

###

GET http://localhost:8000/get/string
